http:
  routers:
    api-router:
      rule: "Host(`api.feats-app.com`) && Method(`GET`, `POST`, `PUT`, `DELETE`, `PATCH`, `OPTIONS`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: api-service
      middlewares:
        - corsHeader

    dashboard-router:
      rule: Host(`dashboard.feats-app.com`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: dashboard-service
      middlewares:
        - dashboard-auth


  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http://api:8000"

    dashboard-service:
      loadBalancer:
        servers:
          - url: "http://traefik"


  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "admin:$$apr1$$laLZLYtc$$/v2XNK/nXb/9dT7qet7P5/"

    corsHeader:
      headers:
        accessControlAllowMethods:
          - GET
          - PATCH
          - PUT
          - POST
          - OPTIONS
        accessControlAllowHeaders: "*"
        accessControlAllowOriginList:
          - https://api.feats-app.com
          - http://api.feats-app.com
          - http://localhost:8100
        accessControlMaxAge: 100
        addVaryHeader: true
