# Generated by Django 4.2.3 on 2024-03-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Allergen name')),
                ('emoji', models.CharField(null=True, verbose_name='Allergen emoji')),
                ('image_url', models.CharField(null=True, verbose_name='Allergen image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Product name')),
                ('allergens', models.ManyToManyField(blank=True, to='product.productallergen')),
            ],
        ),
    ]
