# Generated by Django 4.2.3 on 2024-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productallergen',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='productallergen',
            name='name',
            field=models.CharField(unique=True, verbose_name='Allergen name'),
        ),
    ]
