initial_values = [
    "Carne picada",
    "Carne picada de pollo",
    "Carne picada de ternera",
    "Carne picada de cerdo",
    "Espinacas",
    "Pechuga de pollo",
    "Nata para cocinar",
    "Cebolla",
    "Tomate",
    "Tomate triturado",
    "Tomate frito",
    "Arroz",
    "Cualquier Pasta",
    "Macarrones",
    "Espaguetis",
    "Aceite de oliva",
    "Aceite de girasol",
    "Sal",
    "Pimienta",
    "Patata",
    "Zanahorias",
    "Ajo",
    "Huevos",
    "Leche",
    "Harina",
    "Pan",
    "Queso",
    "Yogur",
    "Lentejas",
    "Garbanzos",
    "Habas",
    "Habichuelas",
    "Salsa de soja",
    "Vinagre",
    "Azúcar",
    "Chocolate",
    "Jamón",
    "Salchichas",
    "Mantequilla",
    "Cacao en polvo",
    "Café",
    "Té",
    "Vino blanco",
    "Vino tinto",
    "Cerveza",
    "Pan rallado",
    "Aceitunas",
    "Pimiento verde",
    "Pimiento rojo",
    "Pimiento amarillo",
    "Limon",
    "Naranjas",
    "Pera",
    "Manzanas",
    "Melocotones",
    "Uvas",
    "Plátanos",
    "Fresas",
    "Sandía",
    "Melón",
    "Piña",
    "Mango",
    "Kiwi",
    "Aguacate",
    "Pepino",
    "Lechuga",
    "Repollo",
    "Brócoli",
    "Coliflor",
    "Judías verdes",
    "Calabacín",
    "Berengena",
    "Calabaza",
    "Remolacha",
    "Apio",
    "Setas",
    "Champiñones",
    "Rúcula",
    "Cilantro",
    "Perejil",
    "Albahaca",
    "Romero",
    "Tomillo",
    "Orégano",
    "Canela",
    "Nuez moscada",
    "Jengibre",
    "Clavos de olor",
    "Comino",
    "Pimentón",
    "Curry",
    "Mostaza",
    "Levadura",
    "Semillas de chía",
    "Semillas de lino",
    "Nueces",
    "Almendras",
    "Cacahuetes",
    "Pistachos",
    "Anacardos",
    "Sésamo",
    "Mantequilla de cacahuete",
    "Mermelada",
    "Miel de abeja",
    "Mermelada de fresa",
    "Nutella",
    "Aceite de coco",
    "Vinagre balsámico",
    "Vinagre de vino",
    "Vinagre de manzana",
    "Vinagre de arroz",
    "Vinagre de Modena",
    "Vinagre de sidra",
    "Queso parmesano",
    "Queso mozzarella",
    "Queso cheddar",
    "Queso feta",
    "Queso ricotta",
    "Queso de cabra",
    "Queso azul",
    "Queso de oveja",
    "Yogur griego",
    "Yogur natural",
    "Leche de almendras",
    "Leche de coco",
    "Leche de avena",
    "Leche de soja",
    "Leche condensada",
    "Leche evaporada",
    "Crema de cacahuete",
    "Crema de avellanas",
    "Crema agria",
    "Crema de leche",
    "Crema de cacao",
    "Crema pastelera",
    "Crema de verduras",
    "Alubias",
    "Guisantes",
    "Frijoles",
    "Maíz",
    "Arroz integral",
    "Cuscús",
    "Quinoa",
    "Avena",
    "Trigo sarraceno",
    "Cebada",
    "Centeno",
    "Pan integral",
    "Pan de centeno",
    "Pan de maíz",
    "Pan de molde",
    "Pan de semillas",
    "Pan de masa madre",
    "Pan de espelta",
    "Pan sin gluten",
    "Tortillas de maíz",
    "Tortillas de trigo",
    "Pasta integral",
    "Pasta de trigo sarraceno",
    "Pasta de espelta",
    "Pasta sin gluten",
    "Hamburguesas vegetarianas",
    "Salchichas vegetarianas",
    "Tofu",
    "Tempeh",
    "Seitan",
    "Levadura nutricional",
    "Algas marinas",
    "Algas nori",
    "Algas kombu",
    "Algas wakame",
    "Algas dulse",
    "Algas espirulina",
    "Algas chlorella",
    "Miso",
    "Tamari",
    "Harina de trigo",
    "Harina de maíz",
    "Harina de centeno",
    "Harina de espelta",
    "Harina de avena",
    "Harina de almendra",
    "Harina de coco",
    "Harina de garbanzo",
    "Harina de arroz",
    "Harina de quinoa",
    "Harina de sorgo",
    "Harina de tapioca",
    "Harina de teff",
    "Harina de boniato",
    "Harina de lentejas",
    "Harina de almendra",
    "Harina de avellana",
    "Harina de nuez",
    "Harina de pistacho",
    "Harina de almendra",
    "Azúcar blanco",
    "Azúcar moreno",
    "Azúcar de coco",
    "Azúcar de caña",
    "Stevia",
    "Panela",
    "Melaza",
    "Mariscos",
    "Ternera",
    "Cerdo",
    "Cordero",
    "Conejo",
    "Pato",
    "Ganso",
    "Pollo",
    "Pavo",
    "Codorniz",
    "Faisán",
    "Oca",
    "Venado",
    "Liebre",
    "Buey",
    "Búfalo",
    "Caracoles",
    "Cangrejo",
    "Pulpo",
    "Calamar",
    "Langosta",
    "Salmón",
    "Atún",
    "Trucha",
    "Sardinas",
    "Anchoas",
    "Bacalao",
    "Merluza",
    "Dorada",
    "Lubina",
    "Besugo",
    "Anguila",
    "Almejas",
    "Ostras",
    "Mejillones",
    "Berberechos",
    "Caviar",
    "Camarones",
    "Langostinos",
    "Gambas",
    "Arenque",
    "Boquerones",
    "Salmón ahumado",
    "Pulpo cocido",
]
