# Generated by Django 4.2.3 on 2024-03-28 16:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_number', models.PositiveIntegerField(verbose_name='User number in the system')),
                ('total_recipe_number', models.PositiveIntegerField(verbose_name='Total Recipes number in the system')),
                ('public_recipe_number', models.PositiveIntegerField(verbose_name='Public Recipes number in the system')),
                ('private_recipe_number', models.PositiveIntegerField(verbose_name='Private Recipes number in the system')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
