# Generated by Django 4.2.3 on 2024-05-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipestep'),
        ('user', '0003_userpreferences_delete_usersettings_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, to='recipe.recipecategory'),
        ),
    ]
