# Generated by Django 4.2.3 on 2024-02-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Product name')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ingredient quantity')),
                ('unit', models.CharField(verbose_name='Measure unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.product')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Food name')),
                ('description', models.CharField(verbose_name='Food description')),
                ('diners', models.PositiveIntegerField(verbose_name='Diners number')),
                ('time', models.PositiveIntegerField(verbose_name='Cooking time in minutes')),
                ('is_public', models.BooleanField(default=True, verbose_name='Recipe status')),
                ('category', models.ManyToManyField(blank=True, to='food.recipecategory', verbose_name='Food categories')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_library.image')),
                ('ingredients', models.ManyToManyField(blank=True, to='food.recipeingredient', verbose_name='Food ingredients')),
            ],
        ),
    ]
