# Generated by Django 4.2.3 on 2024-02-25 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_recipes', to=settings.AUTH_USER_MODEL, verbose_name='User recipe creator'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_recipes', to=settings.AUTH_USER_MODEL, verbose_name='User saved recipes'),
        ),
    ]
