# Generated by Django 4.2.3 on 2024-02-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_recipelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelist',
            name='is_default_list',
            field=models.BooleanField(default=False),
        ),
    ]
