# Generated by Django 4.2.3 on 2024-02-19 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_recipe_is_public_recipe_owner_recipe_saved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Product name')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='food.product'),
            preserve_default=False,
        ),
    ]
